### ISSUE TITLE
CMake Error on Ubuntu 14.04 LTS using CLion 2016.2.3

### ISSUE THREAD

**Issue by ln1equals0** [plstcharles/litiv#10]
Hi, I'm using Ubuntu 14.04 LTS and I direct import the codebase into Clion 2016.2.3, and then the following errors showed up.

![1](https://cloud.githubusercontent.com/assets/10298708/20222280/f6c05dd0-a834-11e6-83ff-799c1d835707.png)

![2](https://cloud.githubusercontent.com/assets/10298708/20222287/fe63dbfc-a834-11e6-9252-3e05d375edac.png)

but I think I've properly installed the opencv, Because I can run some opencv example program successfully.

And when I cmake in terminal, it seems opencv was found.

![3](https://cloud.githubusercontent.com/assets/10298708/20222324/201c6ff2-a835-11e6-8ecf-6a7ce88a02c8.png)

**Comment by plstcharles** [comment]
Hello!

That seems to be an issue with the CMake version and the FindOpenCV.cmake module you're using; if you already have a FindOpenCV.cmake module on your system (typically in /usr/share/cmake/Modules/), you can simply delete the one in the project tree (at litiv/cmake/Modules/), and CMake will fallback to its own. Otherwise, you can still delete the one in the project tree, but you will have to manually specify the path to your OpenCV installation (the true 'manual' mode).

I think I will myself get rid of the FindOpenCV.cmake module I added to the project a couple weeks back --- it's causing more headaches than anything else because it's super old.

**Comment by plstcharles** [comment]
To be more specific: to manually set the path to your OpenCV installation in CMake, set the 'OpenCV_DIR' variable to the OpenCV build output directory, or to the directory where the 'OpenCVConfig.cmake' file resulting from installing the library can be found.
