### ISSUE TITLE
DASC descriptor problem

### ISSUE THREAD

**Issue by excllent123** [plstcharles/litiv#14]
Hi:
     I use DASC descriptor  for learning,but I found your example is hand to understand.
     can you give me an example?
     etc:
     My input is an image , output is DASC descritpr, 
     I use this function  in your library:
     void DASC::compute2(const cv::Mat& oImage, cv::Mat& oDescMap_) 
     but  the output type is
     oDescMap_.type()==CV_32FC1,
     So  how can I get the descritpr? Can you give me another example? 

     Thanks

**Comment by plstcharles** [comment]
Hello!

The 'compute2' extraction function for DASC creates a map; it's first two dimensions are the same as the input image row and column count (let's say, "m x n"), and its third dimension is the descriptor size (fixed by the implementation, 128). To get the descriptor at a single pixel given a map "oDescMap", you can use:
`
oDescMap.ptr<float>(rowidx,colidx)
`
This will return a 128x1 matrix that contains the feature descriptor bin values for the given pixel. Be aware however that descriptors around image borders may be uninitialized; the exact border size is also available through the interface.

The 'compute2' function is however not the standard way to extract descriptor vectors in OpenCV --- instead, the 'compute' function is typically used to extract descriptor vectors one keypoint at a time (using a cv::Mat or an std::vector). In the case of DASC however, it runs the equivalent 'compute2' underneath and samples the correct descriptors (i.e. it always computes the full map), so there's no speed gain.

**Comment by excllent123** [comment]
H:
 In my conputer,The output of compute2  is NULL   
 the size of oDescMap is    (1*-1*-1)
 My code is 

` cv::Mat input = imread("img.bmp");`
`  cv::Mat_<float> output;`
` std::unique_ptr<DASC> pDASC = std::make_unique<DASC>(size_t(2),0.09f);`
` pDASC ->conmpute2(input ,output);`

In  MSVC2015 Update3, Win7 64bit ,the output is NULL,  Can  you point out what's wrong in my code?

**Comment by plstcharles** [comment]
If the `<mat>.create(...)` call has correct arguments (non-null dimensions), and the descriptor matrix is not properly allocated after the call, I can only assume it's an OpenCV problem. Make sure you are using a correct header/lib combination for your platform (same version everywhere!), and a compatible library configuration (release goes with release, debug with debug).

**Comment by excllent123** [comment]
I use opencv3.3 with a compatible library configuration。
if  I add this in DASC
`cv::Mat temp(height,width,MAKETYPE(CV_8U,128))`
`oDescriprot = Mat_<float>(&temp)`


the  output is wright

**Comment by plstcharles** [comment]
Hmm, well, good find if it now works!

I'm trying to understand why this fixes it however, and it makes little sense. First, I'm not sure MAKETYPE can accommodate a 128-channel image (OpenCV limits internal types to 4 channels). Then, the type should be 32F, not 8U, meaning your matrix is actually 4x too small in total byte count. Then, converting to a Mat_<float> from a non-float type (8U=uchar) should throw an exception.

I'll test a bit more on my side when I have time.

**Comment by excllent123** [comment]
I  am sorry  for the error input  .  I have update the code

**Comment by plstcharles** [comment]
How different are the two results? What is 'wrong' in this case? The output is all based on floating point operations, and 32-bit ones instead of 64-bit (Matlab's default). This means that there will be a difference, but it should be minor.

As for debug vs release, it might be visual studio doing strange floating point optimizations --- nothing in the code itself would produce an explicit difference between the two build configs. Unit tests for both configs also pass with the same data on my platforms.

**Comment by excllent123** [comment]
![img](https://user-images.githubusercontent.com/19669013/32476599-5450dfca-c3b3-11e7-9e12-2991eeb05400.PNG)

As you can see   after   
'oDescriprot.create(3,anDescDims.data())'  
'oDescriprot is still  NULL'

If I modify the code, I get the result  below:
The First image is Matlab's result ,The second is the result of Debug ,The third one is release mode:
As you can see, the result is different.    
![matlab](https://user-images.githubusercontent.com/19669013/32476600-5493298e-c3b3-11e7-8c6e-5f282b3349b7.PNG)
![sift1](https://user-images.githubusercontent.com/19669013/32476601-54ca2d9e-c3b3-11e7-9003-56b480310e5c.PNG)
![sift2](https://user-images.githubusercontent.com/19669013/32476602-550653be-c3b3-11e7-905a-091916ff7151.PNG)

**Comment by plstcharles** [comment]
The dasc_rf.regression_single_compute test failing at L45 means that the code was modified somewhere --- the size of a single DASC descriptor should be 128 floats, not 64, and that check is failing. The 128 value is hardcoded through the use of 128-bin LUTs in 'modules/features2d/src/DASC.cpp' --- this might lead to other errors in the following tests.

The dasc_gf.regression_large_compute test failing is strange, as the matrices it tests should be 3-dimensional, and here, the 3rd dimension is in the 6x10^6 range, which is impossible.

I'll set up a new Windows environment this week to test on a fresh clone, but make sure on your side that modifications you made do not break too many things.
