### ISSUE TITLE
Error when try to compile on Mac OS X with GNU GCC 5.3

### ISSUE THREAD

**Issue by lneequals1** [plstcharles/litiv#8]
Try to compile on Mac OS X 10.11 with GNU GCC 5.3, everything is fine with cmake.

But when I start to make, the following error occurs.

![submit](https://cloud.githubusercontent.com/assets/23367116/20155059/662075dc-a6ca-11e6-9cb0-699a935a2d2d.png)

**Comment by plstcharles** [comment]
Hello!

Interesting problem: are you sure you tried to compile with GCC 5.3, and not an older GCC binary? Since 4.8, the '-Wmissing-braces' option should no longer be triggering warnings when using arrays-in-arrays without double braces --- [see here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25137).

If you are in fact using GCC 5.3, it might be caused by some platform-specific issue in GCC --- just confirm it here, and I will patch the top-level CMakeLists.txt for OSX to remove/ignore the '-Wmissing-braces' flag (it is included by default with '-Wall').

-PLSTC

**Comment by lsup888** [comment]
Yeah.., I think that I'm using GCC 5.3.

![s2](https://cloud.githubusercontent.com/assets/23367116/20157376/fa289b88-a6d4-11e6-80bd-268da8261eae.png)

Here is the link to this version of GCC, not sure if it is a motified version.
[http://hpc.sourceforge.net](url)

**Comment by plstcharles** [comment]
Alright, fix is going in then! I patched the top-level CMakeLists.txt in the master branch to disable the culprit flag --- let me know if you have any other issues while compiling (I believe you're the first in quite a few months to compile the framework on OS X.

**Comment by lsup888** [comment]
Hi.. it seems there is another error -Wshadow  in the same file opencv.cpp.

![s3](https://cloud.githubusercontent.com/assets/23367116/20157920/e1371214-a6d7-11e6-91f9-58136ac9c251.png)

I suppose this version of GCC simply doesn't work.

**Comment by plstcharles** [comment]
Well this is very interesting indeed; it seems that the options your GCC was built with make it way more sensitive than the ones I use (4.8.2 and 5.4.0 on Ubuntu). The 'shadowed variable' warning is never triggered on my side, not even on MSVC2015 in super-verbose-mode. In this particular case, the local structure (the object wrapper) cannot use variables from the parent scope, but GCC thinks it can, and acts as if there might be ambiguity between names.

I will patch all the culprit code segments in a few moments --- let's hope that solves it! Besides, to make sure you don't waste too much time on warning-as-errors issues, I will disable this option in CMake for OS X builds. If you do complete a build after that, could you post your compilation output here? I'll try to fix all warnings that pop up.

Thanks for the feedback!

**Comment by lsup888** [comment]
Hi, I think I forgot to tell you that I've manuelly modified the CMakeList.txt to make it run.
I changed the following lines from "Clang" to "AppleClang"

<img width="771" alt="2016-11-10 10 11 27" src="https://cloud.githubusercontent.com/assets/23367116/20170827/3227d220-a72e-11e6-9db2-6ed66ed03d97.png">

Otherwise with "Clang" I get.
<img width="629" alt="2016-11-10 10 15 04" src="https://cloud.githubusercontent.com/assets/23367116/20170924/9fb88b22-a72e-11e6-8a91-785d757c7a33.png">

So I think somehow I'm still using "AppleClang" (or the GNU I'm using is just a wrapper of AppleClang) and with "AppleClang" the compile error changes to:
<img width="960" alt="2016-11-10 10 07 46" src="https://cloud.githubusercontent.com/assets/23367116/20171124/9342bf6a-a72f-11e6-9df3-ff7fa3d99123.png">
 
I modified this line and add tmplate in front of shared_from_this_cast
<img width="1432" alt="2016-11-10 10 29 29" src="https://cloud.githubusercontent.com/assets/23367116/20171401/c3b55f62-a730-11e6-9b13-01cc81dca8e6.png">

then the error becomes 
<img width="947" alt="2016-11-10 10 31 25" src="https://cloud.githubusercontent.com/assets/23367116/20171436/e9f044b2-a730-11e6-8032-28b37f6260a5.png">

it seems AppleClang doesn't know this function.

**Comment by plstcharles** [comment]
Hello again!

I downloaded Clang 3.8 and fixed all the issues I could find on my side. For the missing 'aligned_alloc' function, I wrote a workaround using posix_memalign, which should be available on OS X (although I cannot test it). I also rewrote part of the top-level CMakeLists.txt to properly detect and group 'AppleClang' with regular 'Clang', so both can share compiler options.

Let me know if you run into any more issues!

**Comment by ln1equals0** [comment]
Hi, I think I've already fix all the issues for now, some of those are only work around, here is how.

I switched back to the original "AppleClang" (and GNU GCC still has compile errors on my end)
(For those who don't know, I use macOS 10.11 El Capitan)

![2016-11-12 10 46 25](https://cloud.githubusercontent.com/assets/10298708/20236941/51245246-a8c5-11e6-9a1c-de35d2b22600.png)
 

Fresh download the codebase

1). `mkdir build,
 cd build,
 cmake ..`

CMake Error:
![2016-11-12 10 34 26](https://cloud.githubusercontent.com/assets/10298708/20236875/f924a29a-a8c3-11e6-9197-630015858408.png)

I used this one: 
https://github.com/jevinskie/cmake/blob/master/Modules/CheckFunctionExists.cmake

and add a line in cmakelist.txt
![2016-11-12 10 39 33](https://cloud.githubusercontent.com/assets/10298708/20236891/6115c816-a8c4-11e6-9334-826b59e33916.png)


2)  `make`

![2016-11-12 10 50 42](https://cloud.githubusercontent.com/assets/10298708/20236968/f848aa5e-a8c5-11e6-92af-f053a6f23fbb.png)

I just want to test what other error there is, so I commented the following lines

![2016-11-12 10 54 11](https://cloud.githubusercontent.com/assets/10298708/20236985/61e83b8c-a8c6-11e6-9bc6-51ddf4b480ed.png)

at least posix_memalign works on mac


3) `make` again

![2016-11-12 10 58 07](https://cloud.githubusercontent.com/assets/10298708/20237012/f54f593c-a8c6-11e6-8ab5-1307de02ef9e.png)

it seems the compiler doesn't know the type of nThreshold, so I make the following changes
![2016-11-12 10 59 27](https://cloud.githubusercontent.com/assets/10298708/20237021/1ebcf32e-a8c7-11e6-9e09-5e0edb7df6e8.png)

4) `make` again

![2016-11-12 11 01 19](https://cloud.githubusercontent.com/assets/10298708/20237031/66ce1292-a8c7-11e6-9672-21ae62c24f21.png)

so I added the header file,

![2016-11-12 11 02 18](https://cloud.githubusercontent.com/assets/10298708/20237036/852d47a8-a8c7-11e6-9a50-3fc1d5bd4c48.png)

5) finally the make passed
![2016-11-12 11 04 12](https://cloud.githubusercontent.com/assets/10298708/20237049/e1029e84-a8c7-11e6-9a1a-73fe55e2bc11.png)

and I tested some samples and it works
![2016-11-12 11 07 02](https://cloud.githubusercontent.com/assets/10298708/20237065/319b48a0-a8c8-11e6-9642-a7364d294a4b.png)


the remaining issue: 
GNU GCC both 5.3 and 6.2 doesn't work for me, it has compile error e.g. undefined symbol of cv:: and lv::
and 1) is really just work around, have no idea why HAVE_STL_ALIGNED_ALLOC is not set

Best

**Comment by plstcharles** [comment]
Great, thanks for the feedback!

I will try to patch the framework this afternoon with workarounds for your issues, at least people coming in with similar platform/toolsets might be able to avoid these in the future.
